# pyproject.toml

[project]
name = "fastapi-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[satndard,standard]>=0.135.1",
]

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = [
    "E",   # pycodestyle 기본 규칙
    "F",   # pyflakes (미사용 변수 등)
    "I",   # isort (import 정렬)
    "N",   # 네이밍 규칙
]
ignore = []

# 절대 import만 허용 (상대 import 금지)
[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.vulture]
min_confidence = 80
paths = ["src/"]
ignore_names = ["test_*", "setUp", "tearDown"]
c