"""add markdown csv section support

Revision ID: b336d80334c8
Revises: dfbe6143212a
Create Date: 2026-07-27 23:00:37.766260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b336d80334c8'
down_revision: Union[str, Sequence[str], None] = 'dfbe6143212a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_section',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['app.api_document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.add_column(
        'api_document',
        sa.Column('doc_type', sa.String(length=32), nullable=False, server_default='openapi'),
        schema='app',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_document', 'doc_type', schema='app')
    op.drop_table('api_section', schema='app')
    # ### end Alembic commands ###
