"""initial schema

Revision ID: dfbe6143212a
Revises: 
Create Date: 2026-07-27 22:42:23.776748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'dfbe6143212a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_document',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url'),
    schema='app'
    )
    op.create_table('api_chunk',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('chunk_type', sa.String(length=32), nullable=False),
    sa.Column('ref_id', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=256), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['app.api_document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(
        'ix_api_chunk_embedding_hnsw',
        'api_chunk',
        ['embedding'],
        unique=False,
        schema='app',
        postgresql_using='hnsw',
        postgresql_ops={'embedding': 'vector_cosine_ops'},
    )
    op.create_table('api_endpoint',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('operation_id', sa.String(length=256), nullable=True),
    sa.Column('summary', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['app.api_document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'method', 'path', name='uq_endpoint_doc'),
    schema='app'
    )
    op.create_table('api_schema',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('json_schema', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['app.api_document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'name', name='uq_schema_doc_name'),
    schema='app'
    )
    op.create_table('document_sync_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['app.api_document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('api_parameter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('endpoint_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('location', sa.String(length=32), nullable=False),
    sa.Column('required', sa.Integer(), nullable=False),
    sa.Column('schema_json', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('schema_ref', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['app.api_endpoint.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('api_request_body',
    sa.Column('endpoint_id', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('schema_json', sa.Text(), nullable=False),
    sa.Column('schema_ref', sa.String(length=512), nullable=True),
    sa.Column('required', sa.Integer(), nullable=False),
    sa.Column('example_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['app.api_endpoint.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('endpoint_id'),
    schema='app'
    )
    op.create_table('api_response',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('endpoint_id', sa.String(length=64), nullable=False),
    sa.Column('status_code', sa.String(length=16), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('schema_json', sa.Text(), nullable=False),
    sa.Column('schema_ref', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('example_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['app.api_endpoint.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_response', schema='app')
    op.drop_table('api_request_body', schema='app')
    op.drop_table('api_parameter', schema='app')
    op.drop_table('document_sync_history', schema='app')
    op.drop_table('api_schema', schema='app')
    op.drop_table('api_endpoint', schema='app')
    op.drop_index('ix_api_chunk_embedding_hnsw', table_name='api_chunk', schema='app')
    op.drop_table('api_chunk', schema='app')
    op.drop_table('api_document', schema='app')
    # ### end Alembic commands ###
