"""add source external_id index on document_meta

Revision ID: e2bd26b83408
Revises: 6a3ed3b327a9
Create Date: 2026-08-11 18:08:54.739983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2bd26b83408'
down_revision: Union[str, Sequence[str], None] = '6a3ed3b327a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'ix_document_meta_source_external_id',
        'document_meta',
        ['source', 'external_id'],
        unique=False,
        schema='app',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_meta_source_external_id', table_name='document_meta', schema='app')
    # ### end Alembic commands ###
